### ISSUE TITLE
Missing HUMIDITY Value @ iobroker

### ISSUE THREAD

**Issue by DavidPasch** [jp112sdl/HB-UNI-Sen-CAP-MOIST#10]
Ich hatte Anfang des Jahres mal 2 Sensoren fertig gestellt und alle Werte sauber bekommen und an iobroker übertragen. Leider hatte ich nen Akku Problem - daher erst jetzt dazu gekommen das mit Ladeelektronik zu fixen.

Zwischenzeitlich habe ich das AddOn (2.11) auf meiner CCU2 auch geupdated. Interessanterweise bekomme ich in der CCU2 alle Werte sauber angezeigt, in IObroker habe ich allerdings under dem 2. Kanal des Sensors nicht mehr die HUMIDITY sondern abermals OPERATING_VOLTAGE wie im Kanal 1 - und das auch noch leer.

Neu flashen, ablernen, anlernen - brachte alles keine Besserung. Liegt ein Fehler vor? Wird was nicht sauber übertragen?

**Comment by jp112sdl** [comment]
Hi,
ist ein ioBroker Problem.

https://homematic-forum.de/forum/viewtopic.php?f=76&t=50761&start=30#p518295
