### ISSUE TITLE
Mehrere gleiche Sensortypen an einer CCU2

### ISSUE THREAD

**Issue by TBR-BRD** [jp112sdl/HB-UNI-Sen-CAP-MOIST#11]
Gibt es die Möglichkeit mehrere gleiche Typen https://github.com/jp112sdl/HB-UNI-Sen-CAP-MOIST an einer CCU2 anzulernen? über verschiedene ID oder Serial? Danke

// define all device properties
const struct DeviceInfo PROGMEM devinfo = {
  {0xF3, DEVICE_MODEL, 0x00},  // Device ID
  "JPCAPM0000",                // Device Serial
  {0xF3, DEVICE_MODEL},        // Device Model
  0x10,                        // Firmware Version
  as::DeviceType::THSensor,    // Device Type
  {0x01, 0x01}                 // Info Bytes

**Comment by stan23** [comment]
Das geht, mit unterschiedlicher ID **und**  Serial:
https://asksinpp.de/Grundlagen/02_software.html#device-konfiguration

**Comment by TBR-BRD** [comment]
Danke, das habe ich gesucht.
