### ISSUE TITLE
Sketch auch auf HB-UNI-SEN-BATT möglich?

### ISSUE THREAD

**Issue by Jasimo** [jp112sdl/HB-UNI-Sen-CAP-MOIST#13]
Hallo,

habe noch einige HB-UNI-SEN-BATT Platinen hier und wollte fragen ob ich diese auch für den Sketch einsetzen kann. Anstatt des BME280 würde ich dann einen Bodenfeuchtesensor anschließen. Möchte mal einen Versuch mit der Bodenfeuchte für unseren Rasen im Garten starten.

Gruß
Jan

**Comment by jp112sdl** [comment]
Das Projekt ist nicht an eine Platine gebunden.
Wenn die HB-UNI-SEN-BATT dir Zugang zu den nötigen Pins bereitstellt, sollte nichts dagegensprechen. Oder du änderst im Sketch die Pins entsprechend ab.

**Comment by Jasimo** [comment]
ok, danke für Deine Antwort, dann probiere ich das bei Zeiten mal aus.
