### ISSUE TITLE
Frage zur Lebensdauer der Sensorplatine

### ISSUE THREAD

**Issue by Xento** [jp112sdl/HB-UNI-Sen-CAP-MOIST#14]
Ich habe schon öfters gelesen, dass das PCB der Sensorplatine mit der Zeit Wasser ziehen soll. 
Wie sieht es nach deiner Erfahrung aus?
Sollte man die Platine noch irgendwie vorbehandeln?

**Comment by jp112sdl** [comment]
Hi, ich habe da nix gemacht. Arbeitet noch alles mit dem ersten Sensor zuverlässig.
Habe nur oben die paar Zentimeter mit den Bauteilen ordentlich mit Heißkleber vergossen. 
Wobei es da auch wesentlich elegantere Lösungen gibt ^^
