### ISSUE TITLE
Anlernen geht nicht

### ISSUE THREAD

**Issue by slange112** [jp112sdl/HB-UNI-Sen-CAP-MOIST#15]
Hallo,

ich habe versucht den Sensor nachzubauen und habe folgendes Problem:
Ich kann den Sensor nicht in den Anlernmodus bringen.
Ich habe es mit einem "jungfräulichen" Aufbau (nur Sendeeinheit, Taster und LED) und einen kompletten Aufbau versucht.
Wenn ich aber ein alternatives Programm aufspiele - ich habe das vom 8-Fach Temperatursensor genommen - funktioniert das Anlernen.
Und das auf beiden Boards.

Das Sketch sollte auch richtig aufgespielt worden sein, da die Daten im Seriellen Monitor passen..

Habe nun keinen Plan mehr, was ich noch machen kann.

Grüße

**Comment by jp112sdl** [comment]
> da die Daten im Seriellen Monitor passen..

Zeig bitte mal die Ausgabe komplett

**Comment by slange112** [comment]
Danke für die schnelle Reaktion. 

Das ist der Auszug vom kompletten Board. 

16:02:21.415 -> AskSin++ V4.1.1 (Jul 27 2020 16:00:53)
16:02:21.415 -> Address Space: 32 - 166
16:02:21.415 -> CC init1
16:02:21.415 -> CC Version: 14
16:02:21.449 -> - ready
16:02:21.685 -> iVcc: 3322
16:02:21.685 -> eVcc: 110
16:02:21.685 -> Config Freq: 0x2165CA
16:02:21.786 -> DS18B20 Sensor OK
16:02:21.786 -> ID: F31200 Serial: JPCAPM0000
16:02:21.786 -> *LOW BAT Limit: 22
16:02:21.786 -> *Sendeintervall: 30
16:02:21.786 -> Config changed List1 (CH 1)
16:02:21.786 -> *Offset : 0
16:02:21.786 -> Config changed List1 (CH 2)
16:02:21.786 -> *HIGHValue : 830
16:02:21.786 -> *LOWValue : 420
16:02:21.786 -> Config changed List1 (CH 3)
16:02:21.786 -> *HIGHValue : 830
16:02:21.786 -> *LOWValue : 420
16:02:21.786 -> Config changed List1 (CH 4)
16:02:21.786 -> *HIGHValue : 830
16:02:21.786 -> *LOWValue : 420
16:02:21.786 -> Battery critical! 1 

viele Grüße 

Am 2020-07-27 15:37, schrieb Jérôme:

>> da die Daten im Seriellen Monitor passen..
> 
> Zeig bitte mal die Ausgabe komplett 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/jp112sdl/HB-UNI-Sen-CAP-MOIST/issues/15#issuecomment-664401623
[2]

**Comment by jp112sdl** [comment]
Hab ich fast vermutet ;)

```
16:02:21.685 -> eVcc: 110 
16:02:21.786 -> Battery critical! 1
```

Die externe Spannungsmessung misst 1,1V 
Das liegt weit unter der kritischen Batteriegrenze von 1,9V; die Schaltung geht dann in den Dauerschlaf

**Comment by slange112** [comment]
Ich habe den Programmierer dran. Der Batteriepin ist offen. Da sollte
doch eigentlich die Spannung ausreichen. 

Aber auch mit externen 5V (Netzgerät) funktioniert es nicht. :-( 

Grüße 

Am 2020-07-27 16:07, schrieb Jérôme:

> Hab ich fast vermutet ;)
> 
> 16:02:21.685 -> eVcc: 110 
> 16:02:21.786 -> Battery critical! 1
> 
> Die externe Spannungsmessung misst 1,1V
> Das liegt weit unter der kritischen Batteriegrenze von 1,9V; die Schaltung geht dann in den Dauerschlaf 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/jp112sdl/HB-UNI-Sen-CAP-MOIST/issues/15#issuecomment-664418111
[2]

**Comment by jp112sdl** [comment]
Wie gesagt... so lange die externe Messung nichts > 1,9V misst, wird das nix.

Du kannst gern erstmal Zeile 358 auskommentieren, aber das löst nicht das Problem

**Comment by slange112** [comment]
Das hat funktioniert. :-) 

Kann ich den Programmierer und die externe Spannungsversorgung
gleichzeitig anschließen? Ohne dass was abraucht? 

Dann würde ich noch mal nachschauen, was dann die Aussage für die
Spannung ist. 

Grüße und vielen Dank.  

Am 2020-07-27 18:11, schrieb Jérôme:

> Wie gesagt... so lange die externe Messung nichts > 1,9V misst, wird das nix. 
> 
> Du kannst gern erstmal Zeile 358 auskommentieren, aber das löst nicht das Problem 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/jp112sdl/HB-UNI-Sen-CAP-MOIST/issues/15#issuecomment-664491398
[2]

**Comment by jp112sdl** [comment]
> Kann ich den Programmierer und die externe Spannungsversorgung
gleichzeitig anschließen?

Ja kannst du, da die ext. Spannung an RAW angeschlossen wird, der FTDI aber am VCC klemmt

**Comment by slange112** [comment]
Jetzt laufen 3 Sensonoren.
Vielen Dank für deine Hilfe.
Bin begeistert.
