### ISSUE TITLE
Sensorwerte ändern

### ISSUE THREAD

**Issue by Michel83** [jp112sdl/HB-UNI-Sen-CAP-MOIST#16]
Hallo,

kann es sein das man die Werte in der Web Ui von High und Low der Feuchte nicht mehr ändern kann, leider hat es bei mir ein Sensor zerstört jetzt hatte ich den Fühler gewechselt und wollte die Werte anpassen.

Wenn ich die Werte ändere werden sie Anscheinend zum Sensor gesendet da ich einmal den Knopf an ihm drücken muss aber in der Web  Ui ändern sie sich nicht.

![image](https://user-images.githubusercontent.com/36561525/104047930-c127c580-51e2-11eb-9139-3d47e39ea728.png)

**Comment by jp112sdl** [comment]
CCU FW 3.55.5 ?
Kannst du von irgendeinem anderen (originalen) Gerät die Werte verändern?

Nein? - Dann ist es der ProofAndSetValue Bug in der CCU Firmware.
Findest du im Homematic Forum genug Informationen dazu

**Comment by Michel83** [comment]
Ja habe dies FW, grade mit anderem Original Gerät getestet geht auch nicht.

Danke für die schnelle Antwort.

Grüße
