### ISSUE TITLE
Error while upload

### ISSUE THREAD

**Issue by maxx3105** [jp112sdl/HB-UNI-Sen-CAP-MOIST#2]
Hallo beim flashen bekomme ich diese Fehlermeldung:
Arduino: 1.8.7 (Windows 7), Board: "Arduino Pro or Pro Mini, ATmega328P (3.3V, 8 MHz)"

C:\Program Files\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files\Arduino\hardware -tools C:\Program Files\Arduino\tools-builder -tools C:\Program Files\Arduino\hardware\tools\avr -built-in-libraries C:\Program Files\Arduino\libraries -libraries C:\Users\Markus\Documents\Arduino\libraries -fqbn=arduino:avr:pro:cpu=8MHzatmega328 -ide-version=10807 -build-path C:\Users\Markus\AppData\Local\Temp\arduino_build_257153 -warnings=none -build-cache C:\Users\Markus\AppData\Local\Temp\arduino_cache_182697 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA-1.2.1.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude-6.3.0-arduino14.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc-5.4.0-atmel3.6.1-arduino2.path=C:\Program Files\Arduino\hardware\tools\avr -verbose C:\Users\Markus\Desktop\HB-UNI-Sen-CAP-MOIST\HB-UNI-Sen-CAP-MOIST.ino
C:\Program Files\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files\Arduino\hardware -tools C:\Program Files\Arduino\tools-builder -tools C:\Program Files\Arduino\hardware\tools\avr -built-in-libraries C:\Program Files\Arduino\libraries -libraries C:\Users\Markus\Documents\Arduino\libraries -fqbn=arduino:avr:pro:cpu=8MHzatmega328 -ide-version=10807 -build-path C:\Users\Markus\AppData\Local\Temp\arduino_build_257153 -warnings=none -build-cache C:\Users\Markus\AppData\Local\Temp\arduino_cache_182697 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA-1.2.1.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude-6.3.0-arduino14.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc.path=C:\Program Files\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc-5.4.0-atmel3.6.1-arduino2.path=C:\Program Files\Arduino\hardware\tools\avr -verbose C:\Users\Markus\Desktop\HB-UNI-Sen-CAP-MOIST\HB-UNI-Sen-CAP-MOIST.ino
Using board 'pro' from platform in folder: C:\Program Files\Arduino\hardware\arduino\avr
Using core 'arduino' from platform in folder: C:\Program Files\Arduino\hardware\arduino\avr
Detecting libraries used...
"C:\\Program Files\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=8000000L -DARDUINO=10807 -DARDUINO_AVR_PRO -DARDUINO_ARCH_AVR "-IC:\\Program Files\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "C:\\Users\\Markus\\AppData\\Local\\Temp\\arduino_build_257153\\sketch\\HB-UNI-Sen-CAP-MOIST.ino.cpp" -o nul
HB-UNI-Sen-CAP-MOIST:14:29: error: EnableInterrupt.h: No such file or directory

compilation terminated.

exit status 1
EnableInterrupt.h: No such file or directory

**Comment by maxx3105** [comment]
Ok hab die Libraries nochmal einzeln eingebunden jetzt bekomme ich das.

HB-UNI-Sen-CAP-MOIST:247:21: error: 'printDeviceInfo' was not declared in this scope

     printDeviceInfo();

                     ^

Mehrere Bibliotheken wurden für "EnableInterrupt.h" gefunden
 Benutzt: C:\Users\Markus\Documents\Arduino\libraries\EnableInterrupt
 Nicht benutzt: C:\Users\Markus\Documents\Arduino\libraries\EnableInterrupt-master
Bibliothek EnableInterrupt in Version 0.9.8 im Ordner: C:\Users\Markus\Documents\Arduino\libraries\EnableInterrupt  wird verwendet
Bibliothek AskSinPP-master in Version 2.1.5 im Ordner: C:\Users\Markus\Documents\Arduino\libraries\AskSinPP-master  wird verwendet
Bibliothek Low-Power-master in Version 1.6 im Ordner: C:\Users\Markus\Documents\Arduino\libraries\Low-Power-master  wird verwendet
exit status 1
'printDeviceInfo' was not declared in this scope

**Comment by jp112sdl** [comment]
Ist unwichtig. Kommentier es aus, indem du `//` davor schreibst.

**Comment by maxx3105** [comment]
Super hat geklappt. Danke.
