### ISSUE TITLE
Aktualisierung der ausgelesen Werte 

### ISSUE THREAD

**Issue by pekae** [jp112sdl/HB-UNI-Sen-CAP-MOIST#5]
Hallo

ich verwende die aktuellste Version JP HB 2.7 mit dem CAP-MOIST ohne Temperatursensor.
Derzeit verstehe ich die Datenübermittlung nicht. Es werden mir immer nur Werte angezeigt, die schon vor Stunden übermittelt wurden. Ändert sich der Datenwert (die Feuchtigkeit oder der Batteriewert) nicht, werden anscheinend auch keine (gleichen) Daten gespeichert. Das hat zum "Erfolg", dass mir in der Diagramm-Ansicht mitgeteilt wird, dass für den Sensor noch keine Daten vorliegen. Dies passiert, weil am heutigen Tag die gleichen Werte wie am Vortag übermittelt wurden. Ändere ich das Zeitfenster des Diagramms auf gestern und heute, werden mir die letzten (geänderten) Werte angezeigt. Die danach übermittelten (gleichen) Werte werden nicht angezeigt. Normalerweise müsste eine waagrechte Linie mit gleichen Werten angezeigt werden. Kann ich beeinflussen, dass gleiche Werte auch gespeichert und angezeigt werden ? Im CUX-D Device-Log kann ich sehen, dass der Sensor periodisch Daten übermittelt. Diese werden aber anscheinend nicht verarbeitet, solange es sich um unveränderte Werte handelt.

Danke für Ihre Mühe

Viele Grüße
Peter

**Comment by jp112sdl** [comment]
Hi.
Das hat _leider_ :D nix mit dem Sensor an sich zu tun. Das ist "CCU-Behaviour".

Welches Aktualisierungsintervall hast du eingestellt?
Ich arbeite mit 6 Minuten. Alles darüber hinaus mag die interne Diagramm-Logik der CCU offensichtlich nicht. Dann bekomme ich auch keine Werte angezeigt.

**Comment by pekae** [comment]
Danke für die flotte Antwort 

Ich habe 30 min Intervall eingestellt
Ignoriert der Sensor und sendet alle 10 Minuten 
Ich versuche mal 6 Minuten 
Mal gespannt, ob es ihn interessiert:-)


Mit freundlichen Gruß

Peter Kästner

**Comment by pekae** [comment]
Super, danke
Intervall auf 6 Minuten- schon klappt es mit dem Sensor :-)

Ganz anderes Thema - gibt es einen Trick wie man Systemvariable im Diagramm darstellen kann ? ( ccu-Historian geht , im Diagramm kann man ja nur Geräte auswählen )
Ich übertrage Messwerte über Node Red in Systemvariable , die ich dann gerne im Diagramm hätte. 


Mit freundlichen Gruß

Peter Kästner

**Comment by jp112sdl** [comment]
> gibt es einen Trick wie man Systemvariable im Diagramm darstellen kann ?  

Nein, das geht nicht.

Alles Weitere kann dann im Homematic Forum in den entsprechenden Unterkategorien diskutiert werden, da es sich grundsätzlich nicht auf dieses Projekt bezieht.
