### ISSUE TITLE
Hardware: Sensor arbeitet nicht bei 3,3V

### ISSUE THREAD

**Issue by thkl** [jp112sdl/HB-UNI-Sen-CAP-MOIST#9]
Moin, 
ich habe scheinbar einige eBay Sensoren erwischt, die nicht bei 3,3V arbeiten.

Die Meldung im Log war immer +Analog     (#1): 0 lower than limit!

Daher die Idee den Sensor einfach über einen Transistor direkt an die Batteriespannung zu klemmen. Das scheint erst mal zu funktionieren. Ich werde mal einen Blick auf die Lebensdauer der Batterien werfen.

**Comment by jp112sdl** [comment]
Hmm... da gibts auch verschiedene Versionen des Sensors.
Hast du hast du auch V 1.2 ?

Der Weg mit dem Transistor scheint mir aber auch gangbar.
Ich denke nicht, dass dadurch sonderlich die Stromaufnahme erhöht wird.

**Comment by thkl** [comment]
Ja, V1.2

**Comment by jp112sdl** [comment]
Mittlerweile hat sich herausgestellt, dass es tatsächlich unterschiedliche Bestückungen gibt..
https://homematic-forum.de/forum/viewtopic.php?f=76&t=46658&start=240#p579803

In dem Fall bleibt dann wirklich nur, die externe Spannung per Transistor durchzuschalten.
